### PR TITLE
Improve makefile

### PR DESCRIPTION
**Pull request by TheMrIron2**
Added a background image and a crummy icon (stretched and all, but a placeholder for now!) to demonstrate the use of PIC1/ICON, and I also added some stuff like a commented check to enable large memory for reference.

This didn't compile for me, but my changes weren't the issue - my toolchain must be different from what you're using, and in the interests of not breaking things on your end, I didn't try to fix it. This should work just fine though.

Edit: I did make one mistake that I rectified in a later commit ("Rename icon0 to icon") - the makefile was trying to use "icon.png" when the file in the repository was "icon0.png". I believe my rename commit is part of this pull, but just in case 😃

### CODE REVIEW

**Comment by dbeef** [comment]
Big thanks!

I actually a bit forgot about this demo, I definitely need to make a proper readme for it, at least with building instructions, I am glad that lack of it didn't scare you.

Also, since I created it, I did more programming with OpenGL (though, with modern OpenGL 4.3 / OpenGL ES 3.0 version), so I could get back to this project - I created a reasonable layer of abstraction in SpelunkyDS so it wouldn't be hard to move it to SpelunkyPSP, granting I would take some vacation leave lol.

For the icons and background, I would use those directly from the game, vendored by Spelunky Community Update Project:

https://github.com/tyrovc/SpelunkyCommunityUpdateProject

To make sure it doesn't violate any copyrights; license for using Spelunky Classic assets is clear to me, but I can't tell this about other Spelunky-related assets from the web.

In SpelunkyDS I use this one as an icon in launcher:

https://github.com/tyrovc/SpelunkyCommunityUpdateProject/blob/master/spelunky/Sprites/Items/Treasures/sGoldIdol.images/image%200.png

And this one, after doing something with the alpha channel, could be use as a background:

https://github.com/tyrovc/SpelunkyCommunityUpdateProject/blob/master/spelunky/Sprites/Other/Title/sTitleBG.images/image%200.png

Please upload those instead and I'll merge this. Thanks!

**Comment by TheMrIron2** [comment]
I'll make sure to do that later once I have access to a computer.

On a different note, I wanted to add that I have a reasonably sized PSP discord server now and a lot of people there were very excited to see this project existed, because we were considering remaking (or porting an open source remake) of Spelunky as well! I replied to your SpelunkyDS topic about it on GBAtemp but you hadn't been online since the start of the month so I figured I would commit something to the repo to get your attention.
If you need any help, a few devs there would be happy to help: https://discord.gg/bePrj9W

Great work on this project in any case.

**Comment by TheMrIron2** [comment]
That should do it, let me know how that looks. The background was designed by a friend of mine called Bandithedoge, the icon was a quick thing I put together from the logo.

**Comment by dbeef** [comment]
Thanks Bandithedoge, I'm merging it.

Pleased to hear about the discord server, I'll visit you, at the latest, this weekend. I'll try to write down some roadmap for this project in the meantime. Take care!

**Pull request merged**
